"""Tests for the uv-based dependency resolver."""

import subprocess

import pytest

from pybuild_deps.compile_build_dependencies import (
    ResolvedDependency,
    _parse_compiled_output,
    resolve_with_uv,
)
from pybuild_deps.exceptions import PyBuildDepsError, UnsolvableDependenciesError


def test_resolved_dependency_is_frozen():
    """ResolvedDependency is immutable."""
    dep = ResolvedDependency(name="foo", version="1.0")
    with pytest.raises(AttributeError):
        dep.name = "bar"


def test_parse_compiled_output_collects_every_hash():
    """All --hash lines for a pinned version are captured, comments ignored."""
    text = (
        "# This file was autogenerated by uv\n"
        "#    uv pip compile ...\n"
        "cffi==1.15.1 \\\n"
        "    --hash=sha256:aaa \\\n"
        "    --hash=sha256:bbb \\\n"
        "    --hash=sha256:ccc\n"
        "    # via cryptography\n"
        "wheel==0.40.0 \\\n"
        "    --hash=sha256:ddd\n"
        "setuptools==69.0.0\n"
    )
    results = _parse_compiled_output(text)
    by_name = {r.name: r for r in results}
    assert by_name["cffi"].version == "1.15.1"
    assert by_name["cffi"].hashes == ("sha256:aaa", "sha256:bbb", "sha256:ccc")
    assert by_name["wheel"].hashes == ("sha256:ddd",)
    assert by_name["setuptools"].version == "69.0.0"
    assert by_name["setuptools"].hashes == ()


def test_resolve_raises_when_uv_missing(monkeypatch):
    """A missing uv binary surfaces PyBuildDepsError, not a raw OSError."""

    def _missing(*args, **kwargs):
        raise FileNotFoundError

    monkeypatch.setattr(subprocess, "run", _missing)
    with pytest.raises(PyBuildDepsError):
        resolve_with_uv(["wheel"], package="test")


def test_resolve_raises_on_timeout(monkeypatch):
    """A resolution timeout surfaces PyBuildDepsError."""

    def _timeout(*args, **kwargs):
        raise subprocess.TimeoutExpired(cmd="uv", timeout=300)

    monkeypatch.setattr(subprocess, "run", _timeout)
    with pytest.raises(PyBuildDepsError):
        resolve_with_uv(["wheel"], package="test")


@pytest.mark.e2e
def test_resolve_simple_deps():
    """Resolve a simple dependency list with uv."""
    results = resolve_with_uv(["setuptools>=42", "wheel"], package="test")
    names = {r.name for r in results}
    assert "setuptools" in names
    assert "wheel" in names
    for dep in results:
        assert dep.version


@pytest.mark.e2e
def test_resolve_with_constraints():
    """Constraints pin resolution to specific versions."""
    results = resolve_with_uv(
        ["setuptools>=42"],
        constraints=["setuptools==75.8.2"],
        package="test",
    )
    setuptools = next(r for r in results if r.name == "setuptools")
    assert setuptools.version == "75.8.2"


@pytest.mark.e2e
def test_resolve_with_hashes():
    """--generate-hashes produces hash data."""
    results = resolve_with_uv(["wheel"], generate_hashes=True, package="test")
    wheel = next(r for r in results if r.name == "wheel")
    assert wheel.hashes
    assert any(h.startswith("sha256:") for h in wheel.hashes)


@pytest.mark.e2e
def test_resolve_conflicting_deps():
    """Conflicting deps raise UnsolvableDependenciesError."""
    with pytest.raises(UnsolvableDependenciesError):
        resolve_with_uv(["setuptools>=70", "setuptools<60"], package="test")
