"""compile script."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import IO, Any

import click
from click.utils import LazyFile

from pybuild_deps.compile_build_dependencies import (
    BuildDependencyCompiler,
    ResolvedDependency,
)
from pybuild_deps.exceptions import PyBuildDepsError
from pybuild_deps.logger import log
from pybuild_deps.parsers import parse_requirements


REQUIREMENTS_TXT = "requirements.txt"


@click.command(context_settings={"help_option_names": ("-h", "--help")})
@click.version_option(package_name="pybuild-deps")
@click.pass_context
@click.option("-v", "--verbose", count=True, help="Show more output")
@click.option("-q", "--quiet", count=True, help="Show less output")
@click.option(
    "-n",
    "--dry-run",
    is_flag=True,
    help="Only show what would happen, don't change anything.",
)
@click.option(
    "--header/--no-header",
    is_flag=True,
    default=True,
    help="Add header to generated file",
)
@click.option(
    "-o",
    "--output-file",
    nargs=1,
    default=None,
    type=click.File("w+b", atomic=True, lazy=True),
    help=("Output file name. Will write to stdout by default."),
)
@click.option(
    "--generate-hashes",
    is_flag=True,
    default=False,
    help="Generate pip 8 style hashes in the resulting requirements file.",
)
@click.argument("src_files", nargs=-1, type=click.Path(exists=True, allow_dash=False))
def compile(
    ctx: click.Context,
    verbose: int,
    quiet: int,
    dry_run: bool,
    header: bool,
    output_file: LazyFile | IO[Any] | None,
    generate_hashes: bool,
    src_files: tuple[str, ...],
) -> None:
    """Compiles build-requirements.txt from requirements.txt."""
    log.verbosity = verbose - quiet
    if len(src_files) == 0:
        src_files = _handle_src_files()
    if not output_file and not dry_run:
        log.warning("No output file (-o) specified. Defaulting to 'dry run' mode.")
        dry_run = True

    requirements: list[str] = []
    for src_file in src_files:
        try:
            for req in parse_requirements(src_file):
                req_str = f"{req.name}{req.specifier}"
                if req.url:
                    req_str = f"{req.name} @ {req.url}"
                requirements.append(req_str)
        except PyBuildDepsError as err:
            log.error(str(err))
            sys.exit(2)

    constraints = list(requirements)

    compiler = BuildDependencyCompiler()
    try:
        results = compiler.resolve(
            requirements,
            existing_constraints=constraints,
            generate_hashes=generate_hashes,
        )
    except PyBuildDepsError as e:
        log.error(str(e))
        sys.exit(2)

    _write_output(
        results,
        output_file=None if dry_run else output_file,
        header=header,
        generate_hashes=generate_hashes,
        src_files=src_files,
    )
    if dry_run:
        log.info("Dry-run, so no file created/updated.")


def _write_output(
    results: list[ResolvedDependency],
    *,
    output_file: LazyFile | IO[Any] | None,
    header: bool,
    generate_hashes: bool,
    src_files: tuple[str, ...],
) -> None:
    """Write resolved dependencies as requirements.txt."""
    lines: list[str] = []

    if header:
        lines.append("#")
        lines.append("# This file is autogenerated by pybuild-deps")
        lines.append("#")
        cmd = f"pybuild-deps compile {' '.join(src_files)}"
        if output_file:
            cmd += f" -o {_get_output_name(output_file)}"
        if generate_hashes:
            cmd += " --generate-hashes"
        lines.append(f"#    {cmd}")
        lines.append("#")

    for dep in sorted(results, key=lambda d: d.name.lower()):
        line = f"{dep.name}=={dep.version}"
        if generate_hashes and dep.hashes:
            hash_parts = [f"    --hash={h}" for h in dep.hashes]
            line += " \\\n" + " \\\n".join(hash_parts)
        lines.append(line)

    output = "\n".join(lines) + "\n"

    if output_file:
        _get_stream(output_file).write(output.encode())
    else:
        sys.stdout.write(output)


def _get_output_name(output_file: LazyFile | IO[Any]) -> str:
    if isinstance(output_file, LazyFile):
        return str(output_file.name)
    return str(output_file)


def _get_stream(output_file: LazyFile | IO[Any]) -> IO[bytes]:
    if isinstance(output_file, LazyFile):
        return output_file.open()
    return output_file


def _handle_src_files():
    if Path(REQUIREMENTS_TXT).exists():
        src_files = (REQUIREMENTS_TXT,)
    else:
        raise click.BadParameter(
            f"Couldn't find a '{REQUIREMENTS_TXT}'. "
            "You must specify at least one input file."
        )

    return src_files
